// Auto-generated by ctx.genTypes — do not edit
declare global {
    type Context = import("./$type_Context").Context;

    interface FnsRegistry {
        db: {
        connect: typeof import("./db/connect").default;
        query: typeof import("./db/query").default;
        };
        etl_synthea: {
        createCdm: typeof import("./etl_synthea/createCdm").default;
        createIndices: typeof import("./etl_synthea/createIndices").default;
        createSyntheaTables: typeof import("./etl_synthea/createSyntheaTables").default;
        loadAll: typeof import("./etl_synthea/loadAll").default;
        loadPerson: typeof import("./etl_synthea/loadPerson").default;
        loadSyntheaCsv: typeof import("./etl_synthea/loadSyntheaCsv").default;
        render: typeof import("./etl_synthea/render").default;
        runStep: typeof import("./etl_synthea/runStep").default;
        translate: typeof import("./etl_synthea/translate").default;
        };
        fhir: {
        connect: typeof import("./fhir/connect").default;
        ensureTable: typeof import("./fhir/ensureTable").default;
        init: typeof import("./fhir/init").default;
        loadBundle: typeof import("./fhir/loadBundle").default;
        loadDir: typeof import("./fhir/loadDir").default;
        };
        http: {
        loadRoutes: typeof import("./http/loadRoutes").default;
        match: typeof import("./http/match").default;
        start: typeof import("./http/$start").default;
        };
        mapspec: {
        list: typeof import("./mapspec/list").default;
        render: typeof import("./mapspec/render").default;
        };
        markdown: {
        highlight: typeof import("./markdown/highlight").default;
        mermaid: typeof import("./markdown/mermaid").default;
        render: typeof import("./markdown/render").default;
        };
        profiles: {
        byId: typeof import("./profiles/byId").default;
        load: typeof import("./profiles/load").default;
        profileForEdge: typeof import("./profiles/profileForEdge").default;
        valueSetByUrl: typeof import("./profiles/valueSetByUrl").default;
        viewForEdge: typeof import("./profiles/viewForEdge").default;
        };
        project: {
        classify: typeof import("./project/classify").default;
        roots: typeof import("./project/roots").default;
        scan: typeof import("./project/scan").default;
        };
        repl: {
        eval: typeof import("./repl/eval").default;
        load: typeof import("./repl/load").default;
        start: typeof import("./repl/$start").default;
        };
        viewdef: {
        columns: typeof import("./viewdef/columns").default;
        normalize: typeof import("./viewdef/normalize").default;
        path: typeof import("./viewdef/path").default;
        run: typeof import("./viewdef/run").default;
        };
    }

    interface RootFns {
    genTypes: typeof import("./genTypes").default;
    layout: typeof import("./$layout").default;
    loadFns: typeof import("./loadFns").default;
    }

    namespace types {
        namespace profiles {
            type Profile = import("./profiles/$type_Profile").Profile;
            type ValueSet = import("./profiles/$type_ValueSet").ValueSet;
            type ViewDefinition = import("./profiles/$type_ViewDefinition").ViewDefinition;
        }
    }
}
export {};
