// Auto-generated by ctx.genTypes — do not edit
declare global {
    type Context = import("./$type_Context").Context;

    interface FnsRegistry {
        _test_hashline_edit: {
        nearby: typeof import("../.hyper/_test_hashline_edit/nearby").default;
        };
        http: {
        loadRoutes: typeof import("./http/loadRoutes").default;
        match: typeof import("./http/match").default;
        start: typeof import("./http/$start").default;
        };
        mapspec: {
        list: typeof import("./mapspec/list").default;
        render: typeof import("./mapspec/render").default;
        };
        markdown: {
        highlight: typeof import("./markdown/highlight").default;
        mermaid: typeof import("./markdown/mermaid").default;
        render: typeof import("./markdown/render").default;
        };
        project: {
        classify: typeof import("./project/classify").default;
        roots: typeof import("./project/roots").default;
        scan: typeof import("./project/scan").default;
        };
        repl: {
        eval: typeof import("./repl/eval").default;
        load: typeof import("./repl/load").default;
        start: typeof import("./repl/$start").default;
        };
    }

    interface RootFns {
    genTypes: typeof import("./genTypes").default;
    layout: typeof import("./$layout").default;
    loadFns: typeof import("./loadFns").default;
    }
}
export {};
